// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzXO6EfVrd8fh8J0w8JjDSafWKKZBNdkw',
    appId: '1:564866382155:web:2e98ba45b248c7e48990ce',
    messagingSenderId: '564866382155',
    projectId: 'testingcli-19309',
    authDomain: 'testingcli-19309.firebaseapp.com',
    storageBucket: 'testingcli-19309.appspot.com',
    measurementId: 'G-P1J3ZVBWM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhnlXlfBgRGxD-kRkkV0dktl-iLEYganM',
    appId: '1:564866382155:android:3fd37db40503ac1d8990ce',
    messagingSenderId: '564866382155',
    projectId: 'testingcli-19309',
    storageBucket: 'testingcli-19309.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAppILFNvB49TaE1XgkxhD_Ahxm-JVUYYI',
    appId: '1:564866382155:ios:88acb0322e7212698990ce',
    messagingSenderId: '564866382155',
    projectId: 'testingcli-19309',
    storageBucket: 'testingcli-19309.appspot.com',
    iosBundleId: 'com.beyondsolution.firebaseConnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAppILFNvB49TaE1XgkxhD_Ahxm-JVUYYI',
    appId: '1:564866382155:ios:88acb0322e7212698990ce',
    messagingSenderId: '564866382155',
    projectId: 'testingcli-19309',
    storageBucket: 'testingcli-19309.appspot.com',
    iosBundleId: 'com.beyondsolution.firebaseConnection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzXO6EfVrd8fh8J0w8JjDSafWKKZBNdkw',
    appId: '1:564866382155:web:50ee749dd0c44f6c8990ce',
    messagingSenderId: '564866382155',
    projectId: 'testingcli-19309',
    authDomain: 'testingcli-19309.firebaseapp.com',
    storageBucket: 'testingcli-19309.appspot.com',
    measurementId: 'G-12Z0XCJXXV',
  );
}
